name=Slowino
version=1.0.0
author=Felipe Sallazar
maintainer=Felipe Sallazar <felipesallazar.7@gmail.com>
sentence=Eyes characters patterns and animations for the Slowino LCD partiner.
paragraph=An Arduino library that stores custom 16x2 LCD animated eyes for the Slowino project.
category=Display
url=https://github.com/Sallada07/Slowino
architectures=*