name=EyesAnimations
version=1.0.0
author=Felipe Sallazar
maintainer=Felipe Sallazar <felipesallazar.7@gmail.com>
sentence=LCD eyes animations for the Slowino.
paragraph=An Arduino library that stores custom 16x2 LCD eyes animations for the Slowino project.
category=Display
url=https://github.com/Sallada07/Slowino
architectures=*